type Point = list[float]
type WeightedPoint = tuple[float, Point]

def price_of_kmeans_greedy(points: list[Point]) -> float: ...
def price_of_weighted_kmeans_greedy(points: list[WeightedPoint]) -> float: ...
def price_of_kmedian_hierarchy(points: list[Point]) -> float: ...
def price_of_weighted_kmedian_hierarchy(points: list[WeightedPoint]) -> float: ...
